In [ ]:
# Домашняя работа
import sqlite3
connection = sqlite3.connect('teatchers.db')
cursor = connection.cursor()
query = """CREATE TABLE Students (
Student_Id INTEGER NOT NULL PRIMARY KEY,
Student_Name TEXT NOT NULL,
School_Id INTEGER NOT NULL
);
"""
cursor.execute(query)
connection.commit()
connection.close()

In [ ]:
import sqlite3
connection = sqlite3.connect('teatchers.db')
cursor = connection.cursor()
query = """INSERT INTO Students (Student_Id, Student_Name, School_Id)
VALUES
('201', 'Иван', '1'),
('202', 'Петр', '2'),
('203', 'Анастасия', '3'),
('204', 'Игорь', '4');
"""
cursor.execute(query)
connection.commit()
connection.close()

In [ ]:
import sqlite3

def get_connection():
  connection = sqlite3.connect('teatchers.db')
  return connection

def close_connection(connection):
  if connection:
    connection.close()

def get_school_name(school_id):
  try:
    student_name = get_student_name(school_id)
    connection = get_connection()
    cursor = connection.cursor()
    sql_select_query = """SELECT * FROM Students, School WHERE Students.School_Id = School.School_Id"""
    cursor.execute(sql_select_query, (school_id,))
    records = cursor.fetchall()
    close_connection(connection)
    return records[1]
  except (Exception, sqlite3.Error) as error:
    print ("Ошибка в получении данных", error)

def get_school_detail(school_id):
  try:
    connection = get_connection()
    cursor = connection.cursor()
    select_query = """SELECT * FROM School WHERE School_Id = ?"""
    cursor.execute(select_query,(school_id,))
    records = cursor.fetchall()
    for row in records:
      return row[1]
    close_connection(connection)
  except (Exception, sqlite3.Error) as error:
    print ("Ошибка в получении данных", error)

def get_student_name(school_id):
  try:
    connection = get_connection()
    cursor = connection.cursor()
    select_query = """SELECT * FROM Students WHERE School_Id = ?"""
    cursor.execute(select_query,(school_id,))
    record = cursor.fetchall()
    print ("Студент")
    for row in record:
      print ("ID Студента: ", row[0])
      print ("Имя студента: ", row[1])
      print ("ID школы: ", row[2])
      print ("Название школы:", get_school_detail(school_id))
  except (Exception, sqlite3.Error) as error:
    print ("Ошибка в получении данных", error)


print("Домашняя работа")
get_student_name(1)